name: Convert::EastAsianWidth
version: 0.02
abstract: Convert between full- and half-width characters
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
requires:
  Unicode::EastAsianWidth: 0
generated_by: Module::Install version 0.20
