---
abstract: 'Convert between full- and half-width characters'
author:
  - '唐鳳 <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: CC0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Convert-EastAsianWidth
no_index:
  directory:
    - inc
    - t
provides:
  Convert::EastAsianWidth:
    file: lib/Convert/EastAsianWidth.pm
    version: 1.00
requires:
  perl: 5.8.0
resources:
  repository: http://github.com/audreyt/convert-eastasianwidth
version: 1.00
