--- 
abstract: Convert between full- and half-width characters
author: Audrey Tang <cpan@audreyt.org>
distribution_type: module
generated_by: Module::Install version 0.67
license: mit
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Convert-EastAsianWidth
no_index: 
  directory: 
    - inc
    - t
provides: 
  Convert::EastAsianWidth: 
    file: lib/Convert/EastAsianWidth.pm
    version: 0.10
requires: 
  Unicode::EastAsianWidth: 0
  perl: 5.8.0
version: 0.10
