name: Convert-EastAsianWidth
module_name: Convert::EastAsianWidth
version: 0.03
abstract: Convert between full- and half-width characters
author: Autrijus Tang (autrijus@autrijus.org)
distribution_type: module
requires:
  Unicode::EastAsianWidth: 0
private:
  directory:
    - inc
generated_by: Module::Install version 0.23
